In [1]:
import numpy as np

In [2]:
# Create Array
a = np.array([1,2,3,4])

In [3]:
a

array([1, 2, 3, 4])

In [4]:
b = np.array([[1,2],[3,4]])
b

array([[1, 2],
       [3, 4]])

In [5]:
# Shape
a.shape, b.shape

((4,), (2, 2))

In [6]:
#reshape دوبعدی  Matrix
c = a.reshape(4,1)
c.shape

(4, 1)

In [7]:
#Tensor   چند بعدی 
# d = a.reshape(2,2,1)
d = a.reshape(2,2,-1)
d.shape

(2, 2, 1)

In [8]:
# concatenate 
a = np.array([1,2,3,4])
b = np.array([5,6])
c = np.concatenate((a, b))
c

array([1, 2, 3, 4, 5, 6])

In [9]:
a = np.array([1,2,3])
b = np.array([4,5,6])
# c = a + b
c = a * b
c

array([ 4, 10, 18])

In [10]:
# brodcasting
e = a + 1
e

array([2, 3, 4])

In [11]:
a = np.array([1,2,3,4,5,6,7,8])
a.shape

(8,)

In [12]:

# b = a[1:6]
b = a[1:6:2]
b

array([2, 4, 6])

In [13]:
c = a[a>3]
c

array([4, 5, 6, 7, 8])

In [14]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
sum_a = np.sum(a)
sum_a

np.int64(36)

In [16]:
max_a = np.max(a)
min_a = np.min(a)
max_a, min_a

(np.int64(8), np.int64(1))

In [17]:
a = np.array([3,8,4,1,5,20,12])
b = np.sort(a)
b

array([ 1,  3,  4,  5,  8, 12, 20])

In [18]:
a = np.random.randint(1,20,(3,4))
a

array([[16, 13,  6, 17],
       [ 8, 17, 17,  9],
       [ 5, 17, 13, 10]], dtype=int32)

In [19]:
#create matrix by custom row a column 
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# c = np.vstack((a, b))
c = np.hstack((a, b))
c

array([1, 2, 3, 4, 5, 6])

In [20]:
c.shape

(6,)

In [21]:
#normalize 
mean_a = np.mean(a)
mean_a

np.float64(2.0)

In [22]:
std_a  = np.std(a)
std_a

np.float64(0.816496580927726)

In [23]:
norm_a = (a - mean_a) /std_a
norm_a

array([-1.22474487,  0.        ,  1.22474487])

In [24]:
np.mean(norm_a)

np.float64(0.0)

In [25]:
np.std(norm_a)

np.float64(0.9999999999999999)